version: '3.4'

x-app-service-template: &app
  build: rails_app
  image: yabeda-rails-app:1.0
  volumes:
    - ./rails_app:/app

services:
  rails:
    <<: *app
    ports:
      - ${RAILS_PORT:-5000}:5000
    environment:
      REDIS_URL: redis://redis:6379/0
    stdin_open: true
    tty: true
    depends_on:
      - redis

    command: bundle exec puma -C config/puma.rb

  sidekiq:
    <<: *app
    ports:
      - 5100:5100
    environment:
      PORT: 5100
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

    command: sidekiq -C config/sidekiq.yml

  redis:
    image: redis:6.0.5-alpine
    command: redis-server

  grafana:
    image: grafana/grafana:8.3.4
    depends_on:
      - prometheus    
    ports:
      - 3000:3000/tcp
    volumes: 
      - ./grafana_db:/var/lib/grafana
    user: "104"

  prometheus:
    image: prom/prometheus:v2.33.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    depends_on:
      - rails

    command:
      - --config.file=/etc/prometheus/prometheus.yml

  rails_stressor:
    build: rails_stressor
    image: rails_stressor
    depends_on:
      - rails
    command: -z 2m -c 15 -m GET http://rails:5000
